version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-kidsbugs
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - landing-page
      - api-server
    networks:
      - app-network

  landing-page:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: landing-page-kidsbugs
    restart: always
    networks:
      - app-network

  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api-server-kidsbugs
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      # 필요한 다른 환경 변수들 추가
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot-kidsbugs
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: kidsbugs-network
